/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.EmpList;
import model.Employee;



/**
 *
 * @author Rutu
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    

    /**
     * Creates new form CreateJPanel
     * 
     */
    
    
    EmpList empList;
    
    /*public CreateJPanel(Employee emp) {
        initComponents();
        this.emp = emp;
    }*/
        
    public CreateJPanel(EmpList empList) {
        initComponents();
        this.empList = empList;     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        GenderLaabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        teamInfo = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        cellPh = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        empId_txt = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        level_txt = new javax.swing.JTextField();
        teamInfo_txt = new javax.swing.JTextField();
        pos_txt = new javax.swing.JTextField();
        phNo_txt = new javax.swing.JTextField();
        mailId_txt = new javax.swing.JTextField();
        ImgUpload = new javax.swing.JButton();
        startDate_txt = new javax.swing.JTextField();
        filePath_txt = new javax.swing.JTextField();
        name_txt1 = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        dateFormat = new javax.swing.JLabel();

        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameLabel.setText("Name");

        empID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empID.setText("Employee ID");
        empID.setMinimumSize(new java.awt.Dimension(66, 24));

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setText("Age");

        GenderLaabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenderLaabel.setText("Gender");

        startdateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startdateLabel.setText("Start Date");

        levelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        levelLabel.setText("Level");

        teamInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInfo.setText("Team Info");

        position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        position.setText("Position title");

        cellPh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cellPh.setText("Cell phone number");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Email");

        image.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        image.setText("Image");

        empId_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        age_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gender_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("Enter Employee Details");

        level_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level_txtActionPerformed(evt);
            }
        });

        teamInfo_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInfo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamInfo_txtActionPerformed(evt);
            }
        });

        pos_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pos_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos_txtActionPerformed(evt);
            }
        });

        phNo_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mailId_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ImgUpload.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ImgUpload.setText("Upload");
        ImgUpload.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ImgUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgUploadActionPerformed(evt);
            }
        });

        startDate_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDate_txtActionPerformed(evt);
            }
        });

        filePath_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filePath_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePath_txtActionPerformed(evt);
            }
        });

        name_txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt1ActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setToolTipText("");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        dateFormat.setText("MM/DD/YYY");
        dateFormat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294)
                        .addComponent(ImgUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GenderLaabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(74, 74, 74))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cellPh)
                                        .addComponent(startdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamInfo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pos_txt)
                                    .addComponent(phNo_txt)
                                    .addComponent(level_txt)
                                    .addComponent(mailId_txt)
                                    .addComponent(filePath_txt)
                                    .addComponent(empId_txt)
                                    .addComponent(age_txt)
                                    .addComponent(gender_txt)
                                    .addComponent(name_txt1)
                                    .addComponent(startDate_txt)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addComponent(dateFormat)))))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLaabel)
                    .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startdateLabel)
                    .addComponent(startDate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFormat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levelLabel)
                    .addComponent(level_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamInfo)
                    .addComponent(teamInfo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(position))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellPh)
                    .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(mailId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImgUpload)
                    .addComponent(filePath_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(saveBtn)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teamInfo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamInfo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamInfo_txtActionPerformed

    private void ImgUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImgUploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f1 = chooser.getSelectedFile();
        String filename = f1.getAbsolutePath();
        filePath_txt.setText(filename);
        //Image getAbsolutePath = null;
        //ImageIcon icon = new ImageIcon(filename);
        //Image image = icon.getImage().getScaledInstance(imgLabel.getWidth(),imgLabel.getHeight(),Image.SCALE_SMOOTH);
        //img_view_label.setIcon(icon);
    }//GEN-LAST:event_ImgUploadActionPerformed

    private void pos_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_txtActionPerformed

    private void level_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level_txtActionPerformed

    private void startDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDate_txtActionPerformed

    private void filePath_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePath_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePath_txtActionPerformed

    private void name_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Employee emp1 = new Employee() ;
        
        emp1.setName(name_txt1.getText());
        emp1.setGender(gender_txt.getText());
        emp1.setEmpTeamInfo(teamInfo_txt.getText());
        emp1.setEmpStartDate(startDate_txt.getText());
        emp1.setEmpLevel(level_txt.getText());
        emp1.setEmpID(empId_txt.getText());
        emp1.setEmpAge(age_txt.getText());
        //emp1.setEmailAddress(mailId_txt.getText());
        //emp1.setCellPhoneNo(phNo_txt.getText());
        emp1.setPositionTitle(pos_txt.getText());
        emp1.setImgFilePath(filePath_txt.getText());
        
        String validtel = "\\d{10}";
        Pattern pattern = Pattern.compile(validtel);
        Matcher matcher = pattern.matcher(phNo_txt.getText());
        if (!matcher.matches()){
            JOptionPane.showMessageDialog(this,"Enter correct Cellphone Number");
            return;
        }
        emp1.setCellPhoneNo(phNo_txt.getText());
        
        
       String validemail = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
       Pattern pattern2 = Pattern.compile(validemail);
       Matcher matcher2 = pattern2.matcher(mailId_txt.getText());
       if (!matcher2.matches()){
           JOptionPane.showMessageDialog(this,"Enter corect Email ID");
           return;
       }
       emp1.setEmailAddress(mailId_txt.getText());
       
       
        /*String validDate = "^(1[0-2]|0[1-9])/(3[01]|[12][0-9]|0[1-9])/[0-9]{4}$";
        Pattern pattern3 = Pattern.compile(validDate);
        Matcher matcher3 = pattern3.matcher(phNo_txt.getText());
        if (!matcher3.matches()){
            JOptionPane.showMessageDialog(this,"Enter correct Date");
            return;
        }
        emp1.setEmpStartDate(startDate_txt.getText());*/
       
       
       
        empList.addNewEmployee(emp1);
        
        JOptionPane.showMessageDialog(this,"Details Saved");
        
        name_txt1.setText("");
        gender_txt.setText("");
        teamInfo_txt.setText("");
        startDate_txt.setText("");
        level_txt.setText("");
        empId_txt.setText("");
        age_txt.setText("");
        mailId_txt.setText("");
        phNo_txt.setText("");
        pos_txt.setText("");
        filePath_txt.setText("");
        
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenderLaabel;
    private javax.swing.JButton ImgUpload;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField age_txt;
    private javax.swing.JLabel cellPh;
    private javax.swing.JLabel dateFormat;
    private javax.swing.JLabel email;
    private javax.swing.JLabel empID;
    private javax.swing.JTextField empId_txt;
    private javax.swing.JTextField filePath_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField level_txt;
    private javax.swing.JTextField mailId_txt;
    private javax.swing.JTextField name_txt1;
    private javax.swing.JTextField phNo_txt;
    private javax.swing.JTextField pos_txt;
    private javax.swing.JLabel position;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField startDate_txt;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JLabel teamInfo;
    private javax.swing.JTextField teamInfo_txt;
    // End of variables declaration//GEN-END:variables
}
