/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmpList;
import model.Employee;

/**
 *
 * @author Rutu
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    
    EmpList empList;
    
    public DisplayJPanel(EmpList empList) {
        initComponents();
        this.empList = empList;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        age_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        level_txt = new javax.swing.JTextField();
        startDate_txt = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        GenderLaabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        empId_txt = new javax.swing.JTextField();
        name_txt1 = new javax.swing.JTextField();
        teamInfo_txt = new javax.swing.JTextField();
        pos_txt = new javax.swing.JTextField();
        phNo_txt = new javax.swing.JTextField();
        mailId_txt = new javax.swing.JTextField();
        teamInfo = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        cellPh = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        imgDisplay = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("Employee Details");

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Postion Title", "Level"
            }
        ));
        jScrollPane1.setViewportView(empTable);

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        age_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gender_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        level_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level_txtActionPerformed(evt);
            }
        });

        startDate_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDate_txtActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameLabel.setText("Name");

        empID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empID.setText("Employee ID");
        empID.setMinimumSize(new java.awt.Dimension(66, 24));

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setText("Age");

        GenderLaabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenderLaabel.setText("Gender");

        startdateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startdateLabel.setText("Start Date");

        levelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        levelLabel.setText("Level");

        empId_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        name_txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt1ActionPerformed(evt);
            }
        });

        teamInfo_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInfo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamInfo_txtActionPerformed(evt);
            }
        });

        pos_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pos_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos_txtActionPerformed(evt);
            }
        });

        phNo_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mailId_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        teamInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInfo.setText("Team Info");

        position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        position.setText("Position title");

        cellPh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cellPh.setText("Cell phone number");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Email");

        imgDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(imgDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GenderLaabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDate_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellPh)
                            .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamInfo_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(phNo_txt)
                            .addComponent(level_txt)
                            .addComponent(pos_txt)
                            .addComponent(mailId_txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteBtn, viewBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {age_txt, empId_txt, gender_txt, level_txt, mailId_txt, name_txt1, phNo_txt, pos_txt, startDate_txt, teamInfo_txt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewBtn)
                            .addComponent(deleteBtn))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GenderLaabel)
                                    .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamInfo)
                                    .addComponent(teamInfo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(position))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cellPh)
                                    .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email)
                                    .addComponent(mailId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(startdateLabel)
                                .addComponent(startDate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(levelLabel)
                                .addComponent(level_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteBtn, viewBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void level_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level_txtActionPerformed

    private void startDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDate_txtActionPerformed

    private void name_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt1ActionPerformed

    private void teamInfo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamInfo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamInfo_txtActionPerformed

    private void pos_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_txtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectRowIndex = empTable.getSelectedRow();
        
        if (selectRowIndex < 0){
            JOptionPane.showMessageDialog(this,"Select a row to delete");
            return;        
        }
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        Employee selectEmp = (Employee)model.getValueAt(selectRowIndex, 0);
        
        empList.deleteEmployee(selectEmp);
        
        JOptionPane.showMessageDialog(this,"Employee details deleted");
        populateTable();
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        int selectRowIndex = empTable.getSelectedRow();
        
        if (selectRowIndex < 0){
            JOptionPane.showMessageDialog(this,"Select a row to delete");
            return;        
        }
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        Employee selectEmp = (Employee)model.getValueAt(selectRowIndex, 0);
        
        name_txt1.setText(selectEmp.getName());
        empId_txt.setText(selectEmp.getEmpID());
        age_txt.setText(selectEmp.getEmpStartDate());
        gender_txt.setText(selectEmp.getGender());
        startDate_txt.setText(selectEmp.getEmpStartDate());
        teamInfo_txt.setText(selectEmp.getEmpTeamInfo());
        pos_txt.setText(selectEmp.getPositionTitle());
        phNo_txt.setText(selectEmp.getCellPhoneNo());
        mailId_txt.setText(selectEmp.getEmailAddress());
        level_txt.setText(selectEmp.getEmpLevel());
        
        String filename1 = selectEmp.getImgFilePath();
        //imgDisplay.setText(filename1);
        ImageIcon icon1 = new ImageIcon(filename1);
        imgDisplay.setIcon(icon1);
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        if(empTable.getSelectedRowCount() == 1){
        String name = name_txt1.getText();
        String ID = empId_txt.getText();
        String Age = age_txt.getText();
        String Gender = gender_txt.getText();
        String StDate = startDate_txt.getText();
        String Level = level_txt.getText();
        String Infos = teamInfo_txt.getText();
        String PosTitle = pos_txt.getText();
        String PhNo = phNo_txt.getText();
        String mail = mailId_txt.getText();
        
        
        
        /*empTable.setValueAt(names, empTable.getSelectedRow(), 0);
        empTable.setValueAt(IDs,empTable.getSelectedRow(),1);
        empTable.setValueAt(Ages,empTable.getSelectedRow(),2);
        empTable.setValueAt(Genders,empTable.getSelectedRow(),3);
        empTable.setValueAt(StDates,empTable.getSelectedRow(),4);
        empTable.setValueAt(Levels,empTable.getSelectedRow(),5);
        empTable.setValueAt(Infos,empTable.getSelectedRow(),6);
        empTable.setValueAt(PosTitle,empTable.getSelectedRow(),7);
        empTable.setValueAt(PhNo,empTable.getSelectedRow(),8);
        empTable.setValueAt(mail,empTable.getSelectedRow(),9);*/
        }
        
        
        
        JOptionPane.showMessageDialog(this, "Updated Successfully");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenderLaabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField age_txt;
    private javax.swing.JLabel cellPh;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel email;
    private javax.swing.JLabel empID;
    private javax.swing.JTextField empId_txt;
    private javax.swing.JTable empTable;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JLabel imgDisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField level_txt;
    private javax.swing.JTextField mailId_txt;
    private javax.swing.JTextField name_txt1;
    private javax.swing.JTextField phNo_txt;
    private javax.swing.JTextField pos_txt;
    private javax.swing.JLabel position;
    private javax.swing.JTextField startDate_txt;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JLabel teamInfo;
    private javax.swing.JTextField teamInfo_txt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        model.setRowCount(0);
        
        for(Employee emp: empList.getList()){
            
            Object[] row = new Object[4];
            row[0] = emp;
            row[1] = emp.getName();
            row[2] = emp.getPositionTitle();
            row[3] = emp.getEmpLevel();
            
            model.addRow(row);
            
        }
    }
}
