/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmpList;
import model.Employee;

/**
 *
 * @author Rutu
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     * 
     * 
     */
    
    
    
    EmpList empList;
    int rowNum;
    
    public DisplayJPanel(EmpList empList) {
        initComponents();
        this.empList = empList;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        age_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        level_txt = new javax.swing.JTextField();
        startDate_txt = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        empID = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        GenderLaabel = new javax.swing.JLabel();
        startdateLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        empId_txt = new javax.swing.JTextField();
        name_txt1 = new javax.swing.JTextField();
        teamInfo_txt = new javax.swing.JTextField();
        pos_txt = new javax.swing.JTextField();
        phNo_txt = new javax.swing.JTextField();
        mailId_txt = new javax.swing.JTextField();
        teamInfo = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        cellPh = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        imgDisplay = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("Employee Details");

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Postion Title", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empTable);

        viewBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        age_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        gender_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        level_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level_txtActionPerformed(evt);
            }
        });

        startDate_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDate_txtActionPerformed(evt);
            }
        });

        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameLabel.setText("Name");

        empID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empID.setText("Employee ID");
        empID.setMinimumSize(new java.awt.Dimension(66, 24));

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setText("Age");

        GenderLaabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenderLaabel.setText("Gender");

        startdateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startdateLabel.setText("Start Date");

        levelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        levelLabel.setText("Level");

        empId_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        name_txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt1ActionPerformed(evt);
            }
        });

        teamInfo_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInfo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamInfo_txtActionPerformed(evt);
            }
        });

        pos_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pos_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos_txtActionPerformed(evt);
            }
        });

        phNo_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mailId_txt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        teamInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamInfo.setText("Team Info");

        position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        position.setText("Position title");

        cellPh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cellPh.setText("Cell phone number");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Email");

        imgDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(imgDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GenderLaabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(startDate_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(empId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(name_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellPh)
                                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamInfo_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(phNo_txt)
                                    .addComponent(level_txt)
                                    .addComponent(pos_txt)
                                    .addComponent(mailId_txt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(deleteBtn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGap(35, 35, 35))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteBtn, updateBtn, viewBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {age_txt, empId_txt, gender_txt, level_txt, mailId_txt, name_txt1, phNo_txt, pos_txt, startDate_txt, teamInfo_txt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(empID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(GenderLaabel)
                                    .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamInfo)
                                    .addComponent(teamInfo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(position))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cellPh)
                                    .addComponent(phNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email)
                                    .addComponent(mailId_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(startdateLabel)
                                .addComponent(startDate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(levelLabel)
                                .addComponent(level_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imgDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(viewBtn)
                    .addComponent(deleteBtn))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteBtn, updateBtn, viewBtn});

    }// </editor-fold>//GEN-END:initComponents

    private void level_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_level_txtActionPerformed

    private void startDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDate_txtActionPerformed

    private void name_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt1ActionPerformed

    private void teamInfo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamInfo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamInfo_txtActionPerformed

    private void pos_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_txtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectRowIndex = empTable.getSelectedRow();
        
        if (selectRowIndex < 0){
            JOptionPane.showMessageDialog(this,"Select a row to delete");
            return;        
        }
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        Employee selectEmp = (Employee)model.getValueAt(selectRowIndex, 0);
        
        empList.deleteEmployee(selectEmp);
        populateTable();
        JOptionPane.showMessageDialog(this,"Employee details deleted");
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        int selectRowIndex = empTable.getSelectedRow();
        rowNum = selectRowIndex;
        
        if (selectRowIndex < 0){
            JOptionPane.showMessageDialog(this,"Select a row to delete");
            return;        
        }
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        Employee selectEmp = (Employee)model.getValueAt(selectRowIndex, 0);
        
        name_txt1.setText(selectEmp.getName());
        empId_txt.setText(selectEmp.getEmpID());
        age_txt.setText(selectEmp.getEmpStartDate());
        gender_txt.setText(selectEmp.getGender());
        startDate_txt.setText(selectEmp.getEmpStartDate());
        teamInfo_txt.setText(selectEmp.getEmpTeamInfo());
        pos_txt.setText(selectEmp.getPositionTitle());
        phNo_txt.setText(selectEmp.getCellPhoneNo());
        mailId_txt.setText(selectEmp.getEmailAddress());
        level_txt.setText(selectEmp.getEmpLevel());
        
        String filename1 = selectEmp.getImgFilePath();
        //imgDisplay.setText(filename1);
        ImageIcon icon1 = new ImageIcon(new ImageIcon(filename1).getImage().getScaledInstance(imgDisplay.getWidth(), imgDisplay.getHeight(), Image.SCALE_DEFAULT));
        imgDisplay.setIcon(icon1);
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        //DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        Employee emp1 = (Employee)model.getValueAt(rowNum, 0);
        
        if(empTable.getSelectedRowCount() == 1){
                
        //Employee emp1 = new Employee() ;
        
        emp1.setName(name_txt1.getText());
        emp1.setGender(gender_txt.getText());
        emp1.setEmpTeamInfo(teamInfo_txt.getText());
        emp1.setEmpStartDate(startDate_txt.getText());
        emp1.setEmpLevel(level_txt.getText());
        emp1.setEmpID(empId_txt.getText());
        emp1.setEmpAge(age_txt.getText());
        //emp1.setEmailAddress(mailId_txt.getText());
        //emp1.setCellPhoneNo(phNo_txt.getText());
        emp1.setPositionTitle(pos_txt.getText());
        //emp1.setImgFilePath(filePath_txt.getText());
        
        String validtel = "\\d{10}";
        Pattern pattern = Pattern.compile(validtel);
        Matcher matcher = pattern.matcher(phNo_txt.getText());
        if (!matcher.matches()){
            JOptionPane.showMessageDialog(this,"Enter correct Cellphone Number");
            return;
        }
        emp1.setCellPhoneNo(phNo_txt.getText());
        
        
       String validemail = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
       Pattern pattern2 = Pattern.compile(validemail);
       Matcher matcher2 = pattern2.matcher(mailId_txt.getText());
       if (!matcher2.matches()){
           JOptionPane.showMessageDialog(this,"Enter corect Email ID");
           return;
       }
       emp1.setEmailAddress(mailId_txt.getText());
        
       String validDate = "^(1[0-2]|0[1-9])/(3[01]|[12][0-9]|0[1-9])/[0-9]{4}$";
        Pattern pattern3 = Pattern.compile(validDate);
        Matcher matcher3 = pattern3.matcher(phNo_txt.getText());
        if (!matcher3.matches()){
            JOptionPane.showMessageDialog(this,"Enter correct Date");
            return;
        }
        emp1.setEmpStartDate(startDate_txt.getText());
                        
        name_txt1.setText("");
        gender_txt.setText("");
        teamInfo_txt.setText("");
        startDate_txt.setText("");
        level_txt.setText("");
        empId_txt.setText("");
        age_txt.setText("");
        mailId_txt.setText("");
        phNo_txt.setText("");
        pos_txt.setText("");
        imgDisplay.setIcon(null);
        
        populateTable();      
                
        }
            
               
        JOptionPane.showMessageDialog(this, "Updated Successfully");
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenderLaabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField age_txt;
    private javax.swing.JLabel cellPh;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel email;
    private javax.swing.JLabel empID;
    private javax.swing.JTextField empId_txt;
    private javax.swing.JTable empTable;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JLabel imgDisplay;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField level_txt;
    private javax.swing.JTextField mailId_txt;
    private javax.swing.JTextField name_txt1;
    private javax.swing.JTextField phNo_txt;
    private javax.swing.JTextField pos_txt;
    private javax.swing.JLabel position;
    private javax.swing.JTextField startDate_txt;
    private javax.swing.JLabel startdateLabel;
    private javax.swing.JLabel teamInfo;
    private javax.swing.JTextField teamInfo_txt;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        model.setRowCount(0);
        
        for(Employee emp: empList.getList()){
            
            Object[] row = new Object[4];
            row[0] = emp;
            row[1] = emp.getName();
            row[2] = emp.getPositionTitle();
            row[3] = emp.getEmpLevel();
            
            model.addRow(row);
            
        }
    }
}
